export const mockMovies = [ { title: 'The Phantom Menace',
episode_id: 1,
opening_crawl: 'Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....',
director: 'George Lucas',
producer: 'Rick McCallum',
release_date: '1999-05-19',
characters: 
 [ 'https://swapi.co/api/people/2/',
   'https://swapi.co/api/people/3/',
   'https://swapi.co/api/people/10/',
   'https://swapi.co/api/people/11/',
   'https://swapi.co/api/people/16/',
   'https://swapi.co/api/people/20/',
   'https://swapi.co/api/people/21/',
   'https://swapi.co/api/people/32/',
   'https://swapi.co/api/people/33/',
   'https://swapi.co/api/people/34/',
   'https://swapi.co/api/people/36/',
   'https://swapi.co/api/people/35/' ],
species: 
 [ 'https://swapi.co/api/species/1/',
   'https://swapi.co/api/species/2/',
   'https://swapi.co/api/species/6/',
   'https://swapi.co/api/species/11/',
   'https://swapi.co/api/species/12/',
   'https://swapi.co/api/species/13/',
   'https://swapi.co/api/species/14/',
   'https://swapi.co/api/species/15/',
   'https://swapi.co/api/species/16/',
   'https://swapi.co/api/species/17/',
   'https://swapi.co/api/species/18/',
   'https://swapi.co/api/species/19/',
   'https://swapi.co/api/species/20/',
   'https://swapi.co/api/species/21/',
   'https://swapi.co/api/species/22/',
   'https://swapi.co/api/species/23/',
   'https://swapi.co/api/species/24/',
   'https://swapi.co/api/species/25/',
   'https://swapi.co/api/species/26/',
   'https://swapi.co/api/species/27/' ],
created: '2014-12-19T16:52:55.740000Z',
edited: '2015-04-11T09:45:18.689301Z',
url: 'https://swapi.co/api/films/4/' },
{ title: 'Attack of the Clones',
episode_id: 2,
opening_crawl: 'There is unrest in the Galactic\r\nSenate. Several thousand solar\r\nsystems have declared their\r\nintentions to leave the Republic.\r\n\r\nThis separatist movement,\r\nunder the leadership of the\r\nmysterious Count Dooku, has\r\nmade it difficult for the limited\r\nnumber of Jedi Knights to maintain \r\npeace and order in the galaxy.\r\n\r\nSenator Amidala, the former\r\nQueen of Naboo, is returning\r\nto the Galactic Senate to vote\r\non the critical issue of creating\r\nan ARMY OF THE REPUBLIC\r\nto assist the overwhelmed\r\nJedi....',
director: 'George Lucas',
producer: 'Rick McCallum',
release_date: '2002-05-16',
characters: 
 [ 'https://swapi.co/api/people/2/',
   'https://swapi.co/api/people/3/',
   'https://swapi.co/api/people/6/',
   'https://swapi.co/api/people/7/',
   'https://swapi.co/api/people/10/',
   'https://swapi.co/api/people/11/',
   'https://swapi.co/api/people/20/',
   'https://swapi.co/api/people/21/',
   'https://swapi.co/api/people/22/',
   'https://swapi.co/api/people/33/',
   'https://swapi.co/api/people/36/',
   'https://swapi.co/api/people/35/' ],
species: 
 [ 'https://swapi.co/api/species/32/',
   'https://swapi.co/api/species/33/',
   'https://swapi.co/api/species/2/',
   'https://swapi.co/api/species/35/',
   'https://swapi.co/api/species/6/',
   'https://swapi.co/api/species/1/',
   'https://swapi.co/api/species/12/',
   'https://swapi.co/api/species/34/',
   'https://swapi.co/api/species/13/',
   'https://swapi.co/api/species/15/',
   'https://swapi.co/api/species/28/',
   'https://swapi.co/api/species/29/',
   'https://swapi.co/api/species/30/',
   'https://swapi.co/api/species/31/' ],
created: '2014-12-20T10:57:57.886000Z',
edited: '2015-04-11T09:45:01.623982Z',
url: 'https://swapi.co/api/films/5/' }
]